Mobile skeleton
OpondoG/myPortfolio pull request #4
Opened 2022-07-08 22:27 UTC by OpondoG

2022-07-09 19:28 UTC, algerina reviewed
Hi @OpondoG , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project without a pull request description. Kindly add a description to your pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-09 20:24 UTC, OmarRamoun requested changes
# 🟡 Almost There! 🏃

## Hi @OpondoG 👋

Good job so far! 👏. Your Coding Style is Impressive! 💪.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃

## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** 🌟 that can improve your code quality 💯 and help you **get a better job** 💼.

_I will guide 📔 you through fixing 🔧 these bugs 🐛, just **follow my comments down below** 🔽 and make sure you **don't miss any** of them, in order to get your project approved ✅_

## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

## Required Changes ♻️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 20:24 UTC, OmarRamoun commented on index.html
> +            </div>
- [ ] [REQUIRED] I believe instead of a `<div class="buttons-type">`, use a `<ul>`. Then each of `<input>` can be replaced with a `<li>` This will improve the semantic structure of your website significantly since each of these is in fact a list of information about you and inside it is another list that goes into detail.

2022-07-09 20:24 UTC, OmarRamoun commented on index.html
> +            <img src="assets/img/Snapshoot-Portfolio-PNG.png" alt="Snapshoot">
- [ ] [REQUIRED] Kindly, please, make sure that the card sections are similar to the Figma design. Try to use the same fonts and same colors and also the same border styles.

Your Design | Figma Design
------------|-------------
![image](https://user-images.githubusercontent.com/60979926/178121318-6eedb35e-a1b2-4f4f-b8f3-e51d076effa3.png) | ![image](https://user-images.githubusercontent.com/60979926/178114475-d4ded510-046d-4797-bc45-3ed911dfd4ce.png)

2022-07-09 21:58 UTC, OpondoG commented on index.html
> +            </div>
In the list am not allowed to use any attributes like values and names or type

2022-07-09 22:14 UTC, tufoinnkuo10 requested changes
Hi @OpondoG 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-09 22:14 UTC, tufoinnkuo10 commented on index.html
> +                <div class="projects">
- [ ] like the previous reviewer noted, it will be better you use `ul` in the place of div and `li` for the children

2022-07-09 22:14 UTC, tufoinnkuo10 commented on index.html
> +                    <input type="button" value="javaScript" name="javaScript"></div>
- [ ] you can remove the border color so they look more like the figma version

2022-07-09 22:16 UTC, OpondoG commented on index.html
> +                    <input type="button" value="javaScript" name="javaScript"></div>
but when I use them am being told like this

2022-07-09 22:20 UTC, OpondoG commented on index.html
> +                    <input type="button" value="javaScript" name="javaScript"></div>
where can I contact you @tufoinnkuo10

2022-07-09 22:22 UTC, OpondoG commented on index.html
> +                    <input type="button" value="javaScript" name="javaScript"></div>
![WhatsApp Image 2022-07-10 at 12 49 00 AM](https://user-images.githubusercontent.com/99230309/178124443-1b42891b-7573-4d4e-9c96-6e4c324201f2.jpeg)

2022-07-09 22:23 UTC, OpondoG commented on index.html
> +                    <input type="button" value="javaScript" name="javaScript"></div>
that is when I use ul and li

2022-07-13 15:52 UTC, OmarRamoun commented on index.html
> +            </div>
hello @OpondoG. Sorry for my late reply. I couldn't see the notification on github. Actually, you don't have to use any attributes for this other than `class` for styling purposes. Because the `html`, `css`, `js` are just tags of the card in this website and they are not meant to be semantically interactive.

2022-07-14 10:19 UTC, roshan-bajgain requested changes
Hi @OpondoG, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- PR has a good summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 10:19 UTC, roshan-bajgain commented on index.html
> +                </form>
- [ ] Kindly use the Form that uses the action and method attribute to integrate with [formspree service](https://formspree.io/html). eg:
* `action` value should be similar to `https://formspree.io/f/{form_id}`
* `method` value equals `POST`

2022-07-14 10:19 UTC, roshan-bajgain commented on index.html
> +                    <input type="text" id="name" class="first" placeholder="Gilbert">
- [ ] Name input has `maxlength="30"` attribute. Kindly implement it

2022-07-14 10:19 UTC, roshan-bajgain commented on index.html
> +                    <textarea id="details" class="text-area" placeholder="Write your message here"></textarea>
- [ ] Message input has `maxlength="500"` attribute. kindly implement it

2022-07-14 10:19 UTC, roshan-bajgain commented on index.html
> +                </form>
- [ ] All input fields have the `required` attribute to activate the validation on submit. Kindly implement it as well

2022-07-14 10:19 UTC, roshan-bajgain commented on index.html
> +                </form>
- [ ] Button interactions such as hover, active (when it's pressed), disabled, and enable (default state) are styled as shown in the Figma template.
### Figma design
![his](https://user-images.githubusercontent.com/81727988/178960186-17de5965-5f55-4c80-a2bf-08d667a22ce4.png)

2022-07-14 17:52 UTC, merged